version: "3.8"
services:
  zelus-ide:
    image: zelus-ide
    build:
      cache_from:
        - zelus-ide
      context: .
      dockerfile: zelus-ide.dockerfile
      args:
        - CLOUD_SDK_VERSION
        - PY_VERSION
        - DEBIAN_VERSION
        - POETRY_VERSION
        - PY_PANDAS_VERSION
        - PY_NUMPY_VERSION
        - PY_PYTEST_VERSION
        - PY_PYTEST_MOCK_VERSION
        - PY_GCP_STORAGE_VERSION
        - PY_GCP_BQ_VERSION
        - PY_GCP_BQ_STORAGE_VERSION
        - PY_ZELUS_ENG_UTILS_VERSION
        - ARTIFACTORY_USER
        - ARTIFACTORY_PASSWORD
  personal-ide:
    image: personal-ide
    build:
      cache_from:
        - personal-ide
      context: .
      dockerfile: personal-ide.dockerfile
      args:
        - PY_VERSION
        - DEBIAN_VERSION
        - POETRY_VERSION
        - PY_PANDAS_VERSION
        - PY_NUMPY_VERSION
        - PY_PYTEST_VERSION
        - PY_PYTEST_MOCK_VERSION
